name: HyperChisel
version: '${project.version}'
main: io.github.lianjordaan.hyperchisel.HyperChisel
api-version: 1.19
commands:
  dev:
    description: Teleport to the HyperChisel world
    permission: HyperChisel.dev